# Generated by Django 4.2.30 on 2026-04-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price']},
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, help_text='Short plan tagline'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Highlight as recommended'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on frontend'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10),
        ),
    ]
