# Generated by Django 4.2.30 on 2026-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_options_plan_description_plan_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price', 'id']},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status', 'created_at'], name='payment_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'status', 'created_at'], name='payment_sub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_gateway', 'created_at'], name='payment_gateway_created_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active', 'sort_order', 'price'], name='plan_active_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', 'created_at'], name='subscription_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'expires_at'], name='subscription_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='subscription_plan_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_order_id', ''), _negated=True), fields=('payment_gateway', 'gateway_order_id'), name='uniq_payment_gateway_order_id'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_payment_id', ''), _negated=True), fields=('payment_gateway', 'gateway_payment_id'), name='uniq_payment_gateway_payment_id'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='uniq_active_subscription_per_user'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('starts_at__isnull', True), ('expires_at__isnull', True), ('expires_at__gt', models.F('starts_at')), _connector='OR'), name='subscription_expiry_after_start'),
        ),
    ]
