# Generated by Django 4.2.30 on 2026-04-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Magnivel Media', max_length=200)),
                ('tagline', models.CharField(blank=True, default='A global thought-sharing publication', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('about_text', models.TextField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('default_meta_description', models.TextField(blank=True, default='')),
                ('default_og_image', models.URLField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
